server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mindmapsdb?serverTimezone=UTC
    username: root
    password: admin

  jpa:
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true