// Viewer
export const VIEWER_SET_INPUT_FILE = "VIEWER_SET_INPUT_FILE";
export const VIEWER_DELETE_INPUT_FILE = "VIEWER_DELETE_INPUT_FILE";
export const VIEWER_SET_NODE_ID = "VIEWER_SET_NODE_ID";
export const VIEWER_DELETE_NODE_ID = "VIEWER_DELETE_NODE_ID";
export const VIEWER_SET_NAME = "VIEWER_SET_NAME";
export const VIEWER_DELETE_NAME = "VIEWER_DELETE_NAME";
export const VIEWER_ERROR = "VIEWER_ERROR";
export const VIEWER_RESET_ERROR = "VIEWER_RESET_ERROR";
export const VIEWER_CLEAR_STATE = "VIEWER_CLEAR_STATE";

// User
export const USER_SIGN_UP = "USER_SIGN_UP";
export const USER_SIGN_IN = "USER_SIGN_IN";
export const USER_SIGN_OUT = "USER_SIGN_OUT";
export const USER_ERROR = "USER_ERROR";
export const USER_RESET_ERROR = "USER_RESET_ERROR";
export const USER_LOGGING_IN = "USER_LOGGING_IN";
export const USER_RESET_LOGGING_IN = "USER_RESET_LOGGING_IN";
export const USER_CLEAR_STATE = "USER_CLEAR_STATE";

// Mindmaps
export const MINDMAPS_OWNED_SET_LIST= "MINDMAPS_OWNED_SET_LIST";
export const MINDMAPS_OWNED_RESET_LIST= "MINDMAPS_OWNED_RESET_LIST";
export const MINDMAPS_SHARED_SET_LIST= "MINDMAPS_SHARED_SET_LIST";
export const MINDMAPS_SHARED_RESET_LIST= "MINDMAPS_SHARED_RESET_LIST";
export const MINDMAPS_LOADING = "MINDMAPS_LOADING";
export const MINDMAPS_RESET_LOADING = "MINDMAPS_RESET_LOADING";
export const MINDMAPS_ERROR = "MINDMAPS_ERROR";
export const MINDMAPS_RESET_ERROR = "MINDMAPS_RESET_ERROR";
export const MINDMAPS_CLEAR_STATE = "MINDMAPS_CLEAR_STATE";

// Post form
export const FORM_RESULT = "FORM_RESULT";
export const FORM_RESET_RESULT = "FORM_RESET_RESULT";
export const FORM_ERROR = "FORM_ERROR";
export const FORM_RESET_ERROR = "FORM_RESET_ERROR";
export const FORM_LOADING = "FORM_LOADING";
export const FORM_RESET_LOADING = "FORM_RESET_LOADING";
export const FORM_CLEAR_STATE = "FORM_CLEAR_STATE";

// All
export const CLEAR_ALL_STATE = "CLEAR_ALL_STATE";